let numbers = [ 10,11,12,13,14,15 ];

if (numbers[0] == 10) {
    console.log(10)
}
else if (numbers[1] == 11){
    console.log(11)
}
else if (numbers[2] == 12) {
   console.log(12) 
    
}
else if (numbers[3] == 12){
    console.log(13)
}
else if (numbers[4] == 14){
    console.log(14)
}
 else  (numbers[5] == 15){
    console.log(15)
}



let names = ['nini','elene','gio','nika','saba']

saxelebi.shift()
saxelebi.push('nini')